# Generated by Django 6.0.1 on 2026-01-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_is_active_userprofile_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent_link',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.userprofile'),
        ),
    ]
