# Generated by Django 6.0.1 on 2026-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_parent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
