# Generated by Django 6.0.1 on 2026-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_class_name_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers_assigned', to='accounts.classroom'),
        ),
    ]
