# Generated by Django 6.0.2 on 2026-02-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        ('accounts', '0008_userprofile_assigned_classes'),
    ]

    operations = [
    ]
