# Generated by Django 6.0.1 on 2026-02-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_assigned_classes'),
        ('attendance', '0004_alter_attendance_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.userprofile'),
        ),
    ]
